/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.PilaAlumno;
import Clases.PilaLibro;
import Clases.PilaPrestamo;
import Mostrar.frmMostrarAlumno;
import Mostrar.frmMostrarLibro;
import Mostrar.frmMostrarPrestamo;
import Registrar.frmRegistrarAlumno;
import Registrar.frmRegistrarLibro;
import Registrar.frmRegistrarPrestamo;

/**
 *
 * @author HECTOR MAURICIO
 */
public class frmMenu extends javax.swing.JFrame {

    PilaAlumno datoP = new PilaAlumno();
    PilaLibro datoL = new PilaLibro();
    PilaPrestamo datoE = new PilaPrestamo();
   // String dato;
    
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jbnSalir = new javax.swing.JButton();
        jbnRegresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiRegistrarAlumno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiMostrarAlumno = new javax.swing.JMenuItem();
        jmLibro = new javax.swing.JMenu();
        jmiRegistrarLibro = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiMostrarLibro = new javax.swing.JMenuItem();
        jmPrestamo = new javax.swing.JMenu();
        jmiRegistrar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiMostrar = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        jbnSalir.setText("Salir");
        jbnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSalirActionPerformed(evt);
            }
        });

        jbnRegresar.setText("Regresar");
        jbnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegresarActionPerformed(evt);
            }
        });

        jmAlumno.setText("Alumno");

        jmiRegistrarAlumno.setText("Registrar");
        jmiRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiRegistrarAlumno);
        jmAlumno.add(jSeparator1);

        jmiMostrarAlumno.setText("Mostrar");
        jmiMostrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiMostrarAlumno);

        jMenuBar1.add(jmAlumno);

        jmLibro.setText("Libro");

        jmiRegistrarLibro.setText("Registrar");
        jmiRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarLibroActionPerformed(evt);
            }
        });
        jmLibro.add(jmiRegistrarLibro);
        jmLibro.add(jSeparator2);
        jmLibro.add(jSeparator3);

        jmiMostrarLibro.setText("Mostrar");
        jmiMostrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarLibroActionPerformed(evt);
            }
        });
        jmLibro.add(jmiMostrarLibro);

        jMenuBar1.add(jmLibro);

        jmPrestamo.setText("Prestamo");

        jmiRegistrar.setText("Registrar");
        jmiRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegistrarActionPerformed(evt);
            }
        });
        jmPrestamo.add(jmiRegistrar);
        jmPrestamo.add(jSeparator4);

        jmiMostrar.setText("Mostrar");
        jmiMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMostrarActionPerformed(evt);
            }
        });
        jmPrestamo.add(jmiMostrar);

        jMenuBar1.add(jmPrestamo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jbnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jbnRegresar)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnSalir)
                    .addComponent(jbnRegresar))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarAlumnoActionPerformed
        frmRegistrarAlumno registrarAlumno = new frmRegistrarAlumno(this, datoP);
        registrarAlumno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiRegistrarAlumnoActionPerformed

    private void jmiMostrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarAlumnoActionPerformed

        frmMostrarAlumno mostrarAlumno = new frmMostrarAlumno(this, datoP);
        mostrarAlumno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiMostrarAlumnoActionPerformed

    private void jbnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbnSalirActionPerformed

    private void jbnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegresarActionPerformed
        frmIngreso regresar = new frmIngreso();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbnRegresarActionPerformed

    private void jmiRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarLibroActionPerformed
        frmRegistrarLibro registrarLibro = new frmRegistrarLibro(this, datoL);
        registrarLibro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiRegistrarLibroActionPerformed

    private void jmiMostrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarLibroActionPerformed
        //dato = "Libro\n";
        frmMostrarLibro mortrarLibro = new frmMostrarLibro(this,datoL);
        mortrarLibro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiMostrarLibroActionPerformed

    private void jmiRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegistrarActionPerformed
       frmRegistrarPrestamo registrarPrestamo = new frmRegistrarPrestamo(this, datoE);
       registrarPrestamo.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jmiRegistrarActionPerformed

    private void jmiMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMostrarActionPerformed
        frmMostrarPrestamo mostrarPrestamo = new frmMostrarPrestamo(this, datoE);
        mostrarPrestamo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JButton jbnRegresar;
    private javax.swing.JButton jbnSalir;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmLibro;
    private javax.swing.JMenu jmPrestamo;
    private javax.swing.JMenuItem jmiMostrar;
    private javax.swing.JMenuItem jmiMostrarAlumno;
    private javax.swing.JMenuItem jmiMostrarLibro;
    private javax.swing.JMenuItem jmiRegistrar;
    private javax.swing.JMenuItem jmiRegistrarAlumno;
    private javax.swing.JMenuItem jmiRegistrarLibro;
    // End of variables declaration//GEN-END:variables
}
